### ISSUE TITLE
Using this with certbot and --manual-auth-hook

### ISSUE THREAD

**Issue by galapogos01** [jeansergegagnon/zoneedit_letsencrypt#7]
Hey there,

Thanks for this script! Have you thought of making it work with certbot & --manual-auth-hook without having to use getcert-wilddns-with-zoneedit.sh ?  As in, certbot has its own requets & renewal methods, why implement them again here?

If I am missing something feel free to tell me 😎

Cheers,
Jason

**Comment by galapogos01** [comment]
I forked your repo and implemented this at https://github.com/galapogos01/zoneedit_letsencrypt

Happy to take any feedback.

**Comment by jeansergegagnon** [comment]
Sorry been on vacation.

I'll check that out, thanks
