### ISSUE TITLE
If an TXT SPF record exists in zoneedit script fails

### ISSUE THREAD

**Issue by ddt3** [jeansergegagnon/zoneedit_letsencrypt#9]
An example of a valid SPF record:
`v=spf1 include:spf.migadu.com -all`

This results in the following curl command line options:
`-d TXT::2::host=@ -d TXT::2::txt=v=spf1 include:spf.migadu.com -all -d TXT::2::ttl= `

Where both the white space and the "-all" will  be causing problems.

This results in a txt record where only the first part "v=spf1"  is used which cannot be saved as zoneedit checks SPF records for validity. I would really appreciate it if you could fix  this!

**Comment by jeansergegagnon** [comment]
Yeah, I had the same issue.

Unfortunately, the script can't do anything about that (unless I missed something) as it's a validation that zoneedit does.

I did add a check in the script to abort and not make a broken dns record as output the error that is being sent by Zoneedit.

The workaround is to activate the "ignore spf validation" in the zoneedit options as the error zoneedit is saying that an spf record much contain an IP but the record I had did not and it was given to me by my service provider.

Disabling that check in my zoneedit account solved my problem

**Comment by ddt3** [comment]
This is what happens in my case:
Before I run the script my spf record looks like this:
`v=spf1 include:spf.migadu.com -all`

after running the script the spf record has changed to:
'v=spf1'

Which then indeed does not pass the zoneedit check. Disabling the check indeed makes the script continue but that is besides the point: my spf record no longer is the same.
I am curious to your spf record because it might not need a ip-address but the script removes everything after the first whitespace from the spf record 
'v=spf1'
is not a correct record, so the zoneedit check actually does make sense.

If I could understand how to make curl understand that this:
'-d TXT::2::txt=v=spf1 include:spf.migadu.com -all'

actually should be read as:
'"-d TXT::2::txt=v=spf1 include:spf.migadu.com -all"'
it would solve the problem. But somehow I am not able to make that work which could be cause by the fact that I do not really understand the full script that well :-)

**Comment by ddt3** [comment]
I was still hoping for a response on my previous comment.
Thank you for your time!

**Comment by jeansergegagnon** [comment]
Hi, sorry for missing this - after your comment I did implement a fix locally to my copy and wanted to wait until the next cert update to ensure it worked as expected (that's 3 months)

It's a very small change which I will commit and you can let me know if it solves this for you properly.

Thanks

**Comment by ddt3** [comment]
Would you be able to  share that small fix with me (just tell me which lines to changes or better yet: create a branch, that I can pull). In that way the fix gets tested by 2 persons 
If that is too much of a hassle: I will wait for the fix to be published :-)

Thanks for your work on this!

**Comment by jeansergegagnon** [comment]
It was a single line change and I already published it.

You can see it in last commit.

**Comment by ddt3** [comment]
Just created a wild card domain and it worked flawlessly, keeping my spf record intact. 
Thank you Jean!

**Comment by jeansergegagnon** [comment]
Awesome
